<?php
/**
 * Created by PhpStorm.
 * User: maikuraki
 * Date: 2017/6/26
 * Time: 16:08
 */

namespace backend\controllers;

use yii\web\Controller;

//事件操作
class EventTestController extends Controller
{
    const EVENT_TEST = 'event_test';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->on(self::EVENT_TEST,[$this,'onEventTest']);
    }

    public function actionIndex(){
        $this->trigger(self::EVENT_TEST);
    }

    public function onEventTest(){
        echo 'this a hahaha';
    }
}