<?php
/**
 * Created by PhpStorm.
 * User: maikuraki
 * Date: 2017/8/16
 * Time: 23:58
 */

namespace api\components\event;

use yii\base\Event;

class TextEvent extends Event
{
    //接收者
    public $toUserName;

    //发送者
    public $fromUserName;

    //文本内容
    public $content;

    //创建时间
    public $createTime;

    //消息类型
    private $msgType = 'text';

    //消息模板
    private $template = '<xml><ToUserName><![CDATA[%s]]></ToUserName><FromUserName><![CDATA[%s]]></FromUserName><CreateTime>%s</CreateTime><MsgType><![CDATA[%s]]></MsgType><Content><![CDATA[%s]]></Content></xml>';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->createTime = time();
    }

    /**
     * 获取消息类型
     * @return string
     */
    public function getMsgType(){
        return $this->msgType;
    }

    /**
     * 获取消息模板
     * @return string
     */
    public function getTemplate(){
        return $this->template;
    }
}